import { useEffect, useRef, useState } from 'react';
import '../css/Oybot.css';

// Read API Key from environment variables (.env)
const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;

// Smart Fallback Engine for offline or non-API mode
const getSmartFallbackReply = (userPrompt) => {
    const text = userPrompt.toLowerCase().trim();

    if (/hello|hi|hey|sup|greetings|ola|wazzup|bud|yo/.test(text)) {
        return "Hello! 👋 I'm OyBot, your AI assistant. Ask me anything!";
    }
    if (/thank|thanks|ty|appreciated/.test(text)) {
        return "You're very welcome! 😊 Let me know if you need anything else.";
    }
    if (/bye|goodbye|cya/.test(text)) {
        return "Goodbye! Have a great day ahead! 👋";
    }
    if (/post|report|upload|submit/.test(text)) {
        return "On OyFound, students cannot post or report items directly. All items are posted by campus Admins for safety and accuracy.";
    }
    if (/claim|get my item|receive|lost/.test(text)) {
        return "To claim an item on OyFound:\n1. Browse admin-posted items on the Home page.\n2. Click Claim Item on your item.\n3. An Admin will review your claim under Messages.";
    }
    if (/status|pending|approved|check/.test(text)) {
        return "Check your claim status under Messages. Once approved by an Admin, the status updates automatically.";
    }

    return `I received your message: "${userPrompt}". How else can I help you today?`;
};

// Gemini AI Call — Unrestricted Assistant
const queryGeminiAI = async (userPrompt, chatHistory) => {
    if (!GEMINI_API_KEY || GEMINI_API_KEY === 'your_gemini_api_key_here') {
        return getSmartFallbackReply(userPrompt);
    }

    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}`;

    const formattedContents = [
        ...chatHistory.map(m => ({
            role: m.sender === 'user' ? 'user' : 'model',
            parts: [{ text: m.text }]
        })),
        { role: 'user', parts: [{ text: userPrompt }] }
    ];

    try {
        const response = await fetch(endpoint, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                contents: formattedContents,
                systemInstruction: {
                    parts: [{
                        text: `You are OyBot, a helpful, intelligent, and friendly AI assistant living inside the 'OyFound' campus app.

                        BEHAVIOR INSTRUCTIONS:
                        1. ANSWER EVERYTHING: Respond accurately and helpfully to ANY general question the user asks (e.g., general knowledge, advice, science, programming, chit-chat, greetings, etc.). Never restrict yourself only to OyFound topics.
                        2. OYFOUND KNOWLEDGE: If the user asks specifically about OyFound or lost items:
                           - Note that ONLY Admins can post items (students cannot post/report items directly).
                           - Students browse items posted by Admins on the Home page and click 'Claim Item' to claim.
                           - Claim statuses are tracked under the 'Messages' panel.
                        3. FORMATTING: Keep answers clean, concise, friendly, and easy to read in a small chat widget. Do NOT use markdown bold/asterisks (* or **).`
                    }]
                }
            })
        });

        if (!response.ok) {
            throw new Error(`API error: ${response.status}`);
        }

        const data = await response.json();
        const replyText = data.candidates?.[0]?.content?.parts?.[0]?.text;
        
        // Remove markdown asterisks if generated by AI
        return replyText ? replyText.replace(/\*/g, '') : getSmartFallbackReply(userPrompt);
    } catch (err) {
        console.warn("Gemini API call failed, using fallback responder:", err);
        return getSmartFallbackReply(userPrompt);
    }
};

function Oybot() {
    const [isOpen, setIsOpen] = useState(false);
    const [inputMessage, setInputMessage] = useState("");
    const [isThinking, setIsThinking] = useState(false);
    const [messages, setMessages] = useState([
        {
            id: 1,
            sender: "bot",
            text: "Hi! I'm OyBot 🤖, your AI assistant. Ask me anything!",
            time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
    ]);

    const [position, setPosition] = useState({ x: window.innerWidth - 90, y: window.innerHeight - 90 });
    const [isDragging, setIsDragging] = useState(false);
    const dragRef = useRef({ startX: 0, startY: 0, initialX: 0, initialY: 0, moved: false });
    const messagesEndRef = useRef(null);

    useEffect(() => {
        if (isOpen) {
            messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
        }
    }, [messages, isOpen, isThinking]);

    const handleMouseDown = (e) => {
        setIsDragging(true);
        dragRef.current = {
            startX: e.clientX,
            startY: e.clientY,
            initialX: position.x,
            initialY: position.y,
            moved: false
        };
    };

    const handleTouchStart = (e) => {
        if (!e.touches[0]) return;
        setIsDragging(true);
        dragRef.current = {
            startX: e.touches[0].clientX,
            startY: e.touches[0].clientY,
            initialX: position.x,
            initialY: position.y,
            moved: false
        };
    };

    useEffect(() => {
        const handleMouseMove = (e) => {
            if (!isDragging) return;
            const deltaX = e.clientX - dragRef.current.startX;
            const deltaY = e.clientY - dragRef.current.startY;

            if (Math.abs(deltaX) > 4 || Math.abs(deltaY) > 4) {
                dragRef.current.moved = true;
            }

            const newX = Math.min(Math.max(10, dragRef.current.initialX + deltaX), window.innerWidth - 70);
            const newY = Math.min(Math.max(10, dragRef.current.initialY + deltaY), window.innerHeight - 70);

            setPosition({ x: newX, y: newY });
        };

        const handleTouchMove = (e) => {
            if (!isDragging || !e.touches[0]) return;
            const deltaX = e.touches[0].clientX - dragRef.current.startX;
            const deltaY = e.touches[0].clientY - dragRef.current.startY;

            if (Math.abs(deltaX) > 4 || Math.abs(deltaY) > 4) {
                dragRef.current.moved = true;
            }

            const newX = Math.min(Math.max(10, dragRef.current.initialX + deltaX), window.innerWidth - 70);
            const newY = Math.min(Math.max(10, dragRef.current.initialY + deltaY), window.innerHeight - 70);

            setPosition({ x: newX, y: newY });
        };

        const handleMouseUp = () => {
            setIsDragging(false);
        };

        if (isDragging) {
            window.addEventListener('mousemove', handleMouseMove);
            window.addEventListener('mouseup', handleMouseUp);
            window.addEventListener('touchmove', handleTouchMove);
            window.addEventListener('touchend', handleMouseUp);
        }

        return () => {
            window.removeEventListener('mousemove', handleMouseMove);
            window.removeEventListener('mouseup', handleMouseUp);
            window.removeEventListener('touchmove', handleTouchMove);
            window.removeEventListener('touchend', handleMouseUp);
        };
    }, [isDragging]);

    const handleToggleOpen = () => {
        if (!dragRef.current.moved) {
            setIsOpen(!isOpen);
        }
    };

    const handleSendMessage = async (e) => {
        e.preventDefault();
        if (!inputMessage.trim() || isThinking) return;

        const userText = inputMessage;
        const timeNow = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

        const userMsg = {
            id: Date.now(),
            sender: "user",
            text: userText,
            time: timeNow
        };

        setMessages((prev) => [...prev, userMsg]);
        setInputMessage("");
        setIsThinking(true);

        const aiReply = await queryGeminiAI(userText, messages);

        const botMsg = {
            id: Date.now() + 1,
            sender: "bot",
            text: aiReply,
            time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        };

        setMessages((prev) => [...prev, botMsg]);
        setIsThinking(false);
    };

    return (
        <div 
            className="oybot-wrapper"
            style={{ 
                left: `${position.x}px`, 
                top: `${position.y}px`,
                position: 'fixed',
                zIndex: 9999
            }}
        >
            {!isOpen && (
                <button
                    onMouseDown={handleMouseDown}
                    onTouchStart={handleTouchStart}
                    onClick={handleToggleOpen}
                    className="oybot-toggle-btn"
                    title="Click or drag to open OyBot"
                    style={{ cursor: isDragging ? 'grabbing' : 'grab', userSelect: 'none' }}
                >
                    🤖
                </button>
            )}

            {isOpen && (
                <div className="oybot-modal">
                    <div 
                        className="oybot-header"
                        onMouseDown={handleMouseDown}
                        onTouchStart={handleTouchStart}
                        style={{ cursor: isDragging ? 'grabbing' : 'grab', userSelect: 'none' }}
                    >
                        <div className="oybot-header-info">
                            <div className="oybot-avatar-icon">🤖</div>
                            <div className="oybot-title-stack">
                                <h4>OyBot AI Support</h4>
                                <span className="oybot-status-online">● Online</span>
                            </div>
                        </div>
                        <button
                            onClick={() => setIsOpen(false)}
                            className="oybot-close-btn"
                        >
                            ✕
                        </button>
                    </div>

                    <div className="oybot-body">
                        {messages.map((msg) => (
                            <div
                                key={msg.id}
                                className={`oybot-msg-row ${msg.sender === 'user' ? 'sent' : 'received'}`}
                            >
                                <div className={`oybot-bubble ${msg.sender === 'user' ? 'user' : 'bot'}`}>
                                    {msg.text}
                                </div>
                                <span className="oybot-timestamp">
                                    {msg.time}
                                </span>
                            </div>
                        ))}
                        {isThinking && (
                            <div className="oybot-msg-row received">
                                <div className="oybot-bubble bot" style={{ fontStyle: 'italic', opacity: 0.7 }}>
                                    OyBot is typing...
                                </div>
                            </div>
                        )}
                        <div ref={messagesEndRef} />
                    </div>

                    <form onSubmit={handleSendMessage} className="oybot-footer">
                        <input
                            type="text"
                            placeholder="Ask anything..."
                            value={inputMessage}
                            onChange={(e) => setInputMessage(e.target.value)}
                            className="oybot-input"
                        />
                        <button type="submit" className="oybot-send-btn" disabled={isThinking}>
                            ➔
                        </button>
                    </form>
                </div>
            )}
        </div>
    );
}

export default Oybot;